name: Hourly File Creation

on:
  schedule:
    - cron: '0 0 * */3 *' # Her saat başında çalıştır

jobs:
  create_files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create files
        run: |
          touch deneme.txt

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add hourly files [skip ci]"
          git push
