name: Günlük Sitemap Oluşturma

on:
  schedule:
    - cron: '*/5 * * * *' # Her gün 00:00'da çalıştır

jobs:
  create_sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Generate sitemap
        run: |
          find . \( -path "./blog/" -o -path "./pages/" \) -prune -o -type f -name "*.html" -print > files.txt
          echo '<?xml version="1.0" encoding="UTF-8"?>' > temp_sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> temp_sitemap.xml
          today=$(date +%Y-%m-%d)
          while IFS= read -r line; do
              link=$(echo $line | sed 's/^\.\///' | sed 's/index\.html$//' | sed 's/^\///')
              echo "  <url>" >> temp_sitemap.xml
              echo "    <loc>https://yazilimteknisyeni.com.tr/$link</loc>" >> temp_sitemap.xml
              echo "    <lastmod>$today</lastmod>" >> temp_sitemap.xml
              echo "    <changefreq>daily</changefreq>" >> temp_sitemap.xml
              echo "    <priority>1</priority>" >> temp_sitemap.xml
              echo "  </url>" >> temp_sitemap.xml
          done < files.txt
          echo '</urlset>' >> temp_sitemap.xml
          rm files.txt
          
          #Sitemap dosyasını güncelle
          if [ -f "sitemapi.xml" ]; then
              mv temp_sitemap.xml sitemapi.xml
          else
              mv temp_sitemap.xml sitemapi.xml
          fi

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add sitemapi.xml
          git commit -m "Update sitemap.xml [skip ci]"
          git push
