name: Daily Sitemap Update

on:
  schedule:
    - cron: '*/5 * * * *' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      uses: actions/upload-artifact@v4

    - name: Run Bash Script
      run: bash update_sitemap.sh
