name: Master Sitemap Update

on:
  schedule:
    - cron: '*/9 * * * *' 

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Create a Sitemap
        id: sitemap
        uses: FullStackIndie/sitemap-generator@v1.4.0
        with:
          url: ${{ inputs.url }}
          cache: ${{ inputs.cache }}
          cache-key: ${{ inputs.cache-key }}
          Usage: sitemap https://yazilimteknisyeni.com.tr -p "/directory/to/save/sitemap" -f Daily -L Information
