name: Site Haritası Güncelle

on:
  push:
    branches:
      - mastar  # Ana dalda yapılan değişiklikleri izle, dal adını değiştirebilirsiniz

jobs:
  update-sitemap:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Add HTML files to sitemap
      run: |
        echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
        echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
        find . \( -path "./blog" -o -path "./pages" \) -prune -o -type f -name "*.html" -exec sh -c 'echo "<url><loc>https://yazilimteknisyeni.com.tr/${1//\//}<loc></url>"' _ {} \; >> sitemap.xml
        echo '</urlset>' >> sitemap.xml
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add sitemap.xml
        git commit -m "Update sitemap.xml"
        git push
